Repository mathieucarbou/license-maven-plugin, pull requests merged in 2021-09, with the labels that each got.

#207 license policy enforcement with maven project implementation.
  license-maven-plugin/pom.xml
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/LicenseCheckMojo.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/AbstractLicensePolicyEnforcer.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/AggregateLicensePolicyEnforcer.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/ArtifactLicensePolicyEnforcer.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/DefaultLicensePolicyEnforcer.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicenseMap.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicenseMessage.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicenseNameLicensePolicyEnforcer.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicensePolicy.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicensePolicyEnforcer.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicensePolicyEnforcerResult.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/LicenseURLLicensePolicyEnforcer.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/dependencies/MavenProjectLicenses.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/CheckTest.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/AggregateLicensePolicyEnforcerTest.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/ArtifactLicensePolicyEnforcerTest.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/ArtifactLicensePolicyEnforcerTestBase.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/LicenseNameLicensePolicyEnforcerTest.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/LicensePolicyEnforcerResultTest.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/LicensePolicyTest.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/LicenseURLLicensePolicyEnforcerTest.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/dependencies/MavenProjectLicensesIT.java
  license-maven-plugin/src/test/resources/config/approve/pom.xml
  license-maven-plugin/src/test/resources/config/deny/pom.xml
  license-maven-plugin/src/test/resources/config/null/pom.xml
  pom.xml
Labels: under-review

#220 Adds Maven Wrapper
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  .travis.yml
  mvnw
  mvnw.cmd
  pom.xml
Labels: is:feature, in:build

#221 Fix #187
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/header/HeaderType.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/UpdateMojoTest.java
  license-maven-plugin/src/test/resources/update/issue-187/Main.java
  license-maven-plugin/src/test/resources/update/issue-187/expected.txt
  license-maven-plugin/src/test/resources/update/issue-187/header.txt
Labels: is:bug, in:core

#222 Fix #189
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/document/DocumentType.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/header/HeaderType.java
  license-maven-plugin/src/test/resources/styles/asciidoc_style.txt
Labels: is:enhancement, in:core

#224 Fix #182
  README.md
Labels: is:enhancement, in:doc

#231 Close #158
  .github/workflows/snapshot-report.yml
  license-maven-plugin-git/pom.xml
Labels: is:bug, in:git

#235 Close #26
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/HeaderSection.java
Labels: is:enhancement, in:doc

#237 Features/142
  docs/index.md
  docs/reports/4.2-SNAPSHOT/license-maven-plugin-git/dependencies.html
  docs/reports/4.2-SNAPSHOT/license-maven-plugin-svn/dependencies.html
  docs/reports/4.2-SNAPSHOT/license-maven-plugin/check-mojo.html
  docs/reports/4.2-SNAPSHOT/license-maven-plugin/dependencies.html
  docs/reports/4.2-SNAPSHOT/license-maven-plugin/format-mojo.html
  docs/reports/4.2-SNAPSHOT/license-maven-plugin/remove-mojo.html
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/AbstractLicenseMojo.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/HeaderSection.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/HeaderStyle.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/LicenseSet.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/header/HeaderDefinition.java
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/header/HeaderType.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/AdditionalHeaderMojoTest.java
  license-maven-plugin/src/test/java/com/mycila/maven/plugin/license/CompleteMojoTest.java
Labels: is:feature, in:core
