Repository mathieucarbou/license-maven-plugin, pull requests merged in 2022-01, with the labels that each got.

#257 [type] Support spring.factories as script style comments
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/document/DocumentType.java
Labels: is:enhancement, in:core

#256 [mvn] Update maven wrapper
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: is:enhancement, in:build

#255 [github] Board dependabot
  .github/dependabot.yml
Labels: is:enhancement, in:build

#284 Suppress resource leak warning for instantiated Git object
  license-maven-plugin-git/src/main/java/com/mycila/maven/plugin/license/git/GitLookup.java
Labels: in:core

#283 Suppress resource leaks warnings in FileUtils
  license-maven-plugin/src/main/java/com/mycila/maven/plugin/license/util/FileUtils.java
Labels: in:core
